### ISSUE TITLE
Contact Tracing KickOff issue

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#100]
@codeanticode and @ThomasLengeling here can be a good place to start brainstorming about the contact tracing ABM model.

**Comment by codeanticode** [comment]
I think we should, at least, to incorporate the following parameters:

* App adoption (perhaps as function of age group, see this poll)
* User compliance to the app's alerts
* Time elapsed in getting the alert from the time of contact (due to delay in testing)

As for the implementation, if all individuals keep track of all your past contacts in a list, then this could  be done easily I think:

* After d days, infected individual get tested, at that moment a behavior can be implemented that goes through the list of contacts and sets an "alert" flag in each of of them 
* Based on this flag, contacts will restrict their movement (if they have the app, which is set during initialization based on  app's adoption parameter) according to some compliance probability.

**Comment by agrignard** [comment]
@codeanticode and @ThomasLengeling I am closing for now this issue as @codeanticode has already done it in his project (maybe you could link to your repo here?)

**Comment by codeanticode** [comment]
Relevant links:

* [Source code repo](https://github.com/broadinstitute/ILM-COVID19-risk)
* [arXiv preprint](https://arxiv.org/abs/2006.16761)
