### ISSUE TITLE
404 Not found in MicroSimulationFromMacroMobilityModel.gaml

### ISSUE THREAD

**Issue by ichsan2895** [CityScope/CS_Simulation_GAMA#154]
I have downloaded your repository in [CS GAMA github main page]( https://github.com/CityScope/CS_Simulation_GAMA). Then, I tried to execute `MicroSimulationFromMacroMobilityModel.gaml`.

Then, It was an error called` 404 Not Found`. There are not available a link called `pt_net.geojson` . Let me browse that github for sure. Here is the link [CS_Mobillity Services in Github](https://raw.githubusercontent.com/CityScope/CS_Mobility_Service/master/scripts/cities/Detroit/clean/pt_net.geojson)

**Comment by agrignard** [comment]
Hi @ichsan2895 ,
Thank you for rising this, there is indeed an issue which is already documented here https://github.com/CityScope/CS_Mobility_Service/issues/41. @doorleyr and I are workong on it and hopefully will close it soon.

**Comment by agrignard** [comment]
This issue is now fixed thanks to this one https://github.com/CityScope/CS_Mobility_Service/issues/41

You can now run the MicroSimulation model we you should have this visualization. I Close this issue for now please feel free to reopen it if something goes wrong.

<img width="963" alt="Screenshot 2020-11-25 at 09 59 39" src="https://user-images.githubusercontent.com/3928502/100205105-f8793600-2f04-11eb-94d8-826e30b560fd.png">
