### ISSUE TITLE
Visualization Design/Discussion

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#89]
People Aspect: The "tails" are the important part, not the “dots”, So: Smaller and more transparent dots. More diversity of agents (color)?

@LAAP what do we want to show in the color? So far we don't have profile of people (and I am fraid it will complexify the rendering but let's see), they are all the same

**Comment by LAAP** [comment]
@agrignard , You are wright, maybe in this iteration we can keep the same color that will change with the "infection" (they became red, death = black, recovered = green)

However, maybe in future iterations we could have some profiles: Workers at home, commuters mass transportation, workers that walk from home to work, etc... It could be in a range of "blue colors", very subtle, but enough to tell the different behaviours

**Comment by agrignard** [comment]
You can now play with the people transparency from the parameter (let me know which value is the good one)

**Comment by LAAP** [comment]
Thanks @agrignard 

1) In the GotoOnNetworkAgent: I see that we can play with the transparency of people but not the "buses/trains/commute elements".

2) In the CoronaMap: Agents are not being affected

**Comment by agrignard** [comment]
Ok you have a people and macro transparency now (it could be the same for both but I have differentiated them)

I close this issue, and can you create a more specific one for point 2 (peopel are not infected)

**Comment by LAAP** [comment]
Hi @agrignard, I think that you misunderstood my point "2":

I have said, "In the CoronaMap: Agents are not being **affected**" (I mean, the transparency doesn't affect the agents in the "CoronaMap" model, but you understood **"infected"**

So, I think that it doesn't makes sense to open a new issue for that.

I am closing also this issue, again

**Comment by agrignard** [comment]
ah ok sorry i understood infected, yes indeed the transparency are not implemented in the CoronaMap, it can be done if needed yes.

**Comment by agrignard** [comment]
See https://github.com/CityScope/CS_Simulation_GAMA/issues/92

**Comment by LAAP** [comment]
@agrignard Can we play with the "expression" of the agents?. Can we play with variable thickness, transparency, etc. in the tail? Different size of circles and squares, or other geometries.... etc? I think that we need to rethink this for the future models

**Comment by agrignard** [comment]
Yes we can do whatever expression for the agent we want of course (playing with color, shapes, size etc) . The question is not technical but what do we want to show?

**Comment by LAAP** [comment]
Hi @agrignard, I think that this is more about "the wow effect". Exploring some visual stuff. I know that storytelling is very important (but we are already talking about that in a different issue) , but at the end of the day we ant to tell diversity of people moviments, interaction between people and with buildings and neighborhoods... So I think this issue is about exploring new visual stuff. I send you some examples as an inspiration (¿?):


![global-immigration-map](https://user-images.githubusercontent.com/19315213/80983565-ad79c300-8dfa-11ea-813b-92005b8ef973.png)

![Bird_Migration_Western_Map_v25_btj_dark_reproj-Artboard_2](https://user-images.githubusercontent.com/19315213/80983385-7efbe800-8dfa-11ea-8c20-f110bacf1579.jpg)

![birds](https://user-images.githubusercontent.com/19315213/80983399-828f6f00-8dfa-11ea-8b3d-534eeaa6f178.gif)

![BlackMarble_2016_3km_geo_flyways](https://user-images.githubusercontent.com/19315213/80983413-858a5f80-8dfa-11ea-9e41-08464ce97f0c.jpg)

![cryptolocker-bfs4](https://user-images.githubusercontent.com/19315213/80983427-89b67d00-8dfa-11ea-89f0-75956d947d2b.jpg)

![world-trade-live](https://user-images.githubusercontent.com/19315213/80983445-8d4a0400-8dfa-11ea-86f0-0a263f243218.jpg)

![mosaic](https://user-images.githubusercontent.com/19315213/80983469-93d87b80-8dfa-11ea-9d97-bb4015d1f761.gif)

![Map_of_North_America_Species_Migration_4000x2200](https://user-images.githubusercontent.com/19315213/80983500-9b982000-8dfa-11ea-89b0-fa0fbaa8361d.jpg)

![jBfXb](https://user-images.githubusercontent.com/19315213/80983510-9fc43d80-8dfa-11ea-9fb0-34f9d0f97947.png)

![InsistentFeistyGrouse-size_restricted](https://user-images.githubusercontent.com/19315213/80983532-a3f05b00-8dfa-11ea-8f14-41ca8184209a.gif)

![darkecologyp](https://user-images.githubusercontent.com/19315213/80983627-bff3fc80-8dfa-11ea-96a3-fd7deb5d5157.png)

**Comment by agrignard** [comment]
I close this one for now who is a bit to conceptual
