### ISSUE TITLE
KPIs for City Efficiency

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#90]
1.  Number of trips = Walk (inside the cell) versus Mass transportation (Between cells)
2.  Working time = Number of agents working and achieving the goal of working from home or at the office
3.  Environmental impact = % of trips between cells versus walking trips
4.  The sum of these 3 parameters will give us an “Energy-bar indicator” named “Efficiency of the city

**Comment by agrignard** [comment]
Trying to work on this KPIS but to implement it there is some part that doesn't make sense to me.

For instance what's the difference between 1 and 3 ? (it's walk vs mass in both case)

For point 2 how do we compute the working time? Knowing that this model was to show the commuting (people don't stay at work in this model, should I count a soon as you reach your office?

**Comment by agrignard** [comment]
First iteration (only comparing the walk  vs mass) 

<img width="1920" alt="Screenshot 2020-05-05 at 11 08 43" src="https://user-images.githubusercontent.com/3928502/81050782-e4b2a780-8ec0-11ea-8247-3bccc70fd89a.png">

<img width="1920" alt="Screenshot 2020-05-05 at 11 08 59" src="https://user-images.githubusercontent.com/3928502/81050780-e3817a80-8ec0-11ea-8f1d-82b450f8a878.png">

**Comment by LAAP** [comment]
Hi @agrignard ,

It is looking very good. I will test the simulation ASAP. In the midterm, maybe the Mas transportation can be in a different color than red (it is "dangerous" to use,  but not "bad" because it is sustainable), Maybe orange or grey or similar

**Comment by LAAP** [comment]
> Trying to work on this KPIS but to implement it there is some part that doesn't make sense to me and we don't compare apple to apple here
> 
> For instance what's the difference between 1 and 3 ? (it's walk vs mass in both case)
> 
> For point 2 how do we compute the working time? Knowing that this model was to show the commuting (people don't stay at work in this model, should I count a soon as you reach your office?

Hi @agrignard , Yes, you are correct, 1 and 3 are today the same. But we could make something more interesting trying to translate people's behaviour from (https://github.com/CityScope/CS_Simulation_GAMA/issues/99#issuecomment-623550852) into CO2, so then, maybe we can measure the impact in enegy of people working at home vs workers (mobility but also building energy), etc.

Maybe we can use this old "educated guest" numbers:


Units | Housing | Normal office
-- | -- | --
Area: m2 per capita | 89 | 18,3333
Consumption: kWh per capita | 5930,34 | 4652,8
Pollution production: Kg CO2 per capita | 2283,18 | 1791,328


Regarding point 2, we can use the profiles at issue (https://github.com/CityScope/CS_Simulation_GAMA/issues/99#issuecomment-623550852) about how to "3) Visualizing the pandemic: ", in order to see how pandemic reduce working force and time as soon as they get sick. So the working time is 8h per day (40h week) and as soon as people gets sick, this can drop:

-Healthy: 8h of work
-Sick asymptomatic: 7h (because you do not feel 100%)
-Sick symptomatic: 4h (because probably some of them will work from home even when sick)
-Death: 0h
-Recovered: 8h of work
