### ISSUE TITLE
KPIs for PANDEMIC IMPACT

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#91]
1.  Number of infections
2.  Number of deaths (?)
3.  Number of recoveries (?)
4. Number of occupied beds in Hospitals(?)

**Comment by agrignard** [comment]
1,2 and 3 are already there in the coronaChart (when launching CityScope_coronaizer.gaml)

<img width="1326" alt="Screenshot 2020-04-27 at 12 25 51" src="https://user-images.githubusercontent.com/3928502/80362216-8cf1bc00-8882-11ea-997e-9aef8be70888.png">


For the hospital, we can have a ratio that says that ones you are infected you have a probability to go there, however where is the hospital in this case? Do we want to see peopel there or just "remove them" from the equation

**Comment by LAAP** [comment]
Hi @agrignard . This is Great. But I am confused, I thought that "CityScope_coronaizer.gaml" and "Autonomous_Covid_Community model " are two separate models. How can I run both at the same time?

**Comment by agrignard** [comment]
when you look at the code of 
`````
CityScope_coronaizer.gaml
``````
you will see at the first line

`````
import "Autonomous_Covid_Community.gaml"
`````

CityScope_coronaizer is a kind of plugin that can import "any" compatible model (basically having a species people that s moving and can plug on top of it an SIR model to monitor the spreading of a virus. So we do'nt have to rewrite always this model but jsut plug it on any GAMA model to analyse the virus spreading.

So if you run Autonomous_Covid_Community you just have the people movign if you run 
CityScope_coronaizer you have Autonomous_Covid_Community+the Covid stuff

**Comment by LAAP** [comment]
**Hospital:** @agrignard this is a good question. We have a lot of different options. But what do you think about this scenario?:

**A) Generic numbers:**

1) We need to find the ratio of people using a hospital bed because  of this pandemic: between 15 days and 35 days? (Maybe this is a slider?)
2) We need to find the latest data about % of infected people who needs a normal bed, a medicalised bed, or goes asymptomatic 
3) We need to find the number of medicaliced beds per hospital: between 5 and 20? (other slider?)
4) We need to find the number of normal beds in hospitals: between 50-100-200? (other slider?)
5) We need to find the ratios of people passing away when they have no access to hospitals versus when they have access to hospitals

**B) Scenarios:**

-Common setting: Maybe we have a centralized general Hospital in the Business district (Conventional) and in the Low-right circle (Autonomous) with "X" number of beds (slider) and "Y" number of medicaliced beds (slider)

**-Conventional:** People gets sick and after 15 days (more or less), the symptomatic (a " X" %) goes to the hospital, the very sick goes to the medicalized bed, the normal sick goes to a normal hospital bed where they recover faster than at home, and reduces the chance to go to a medicalized bed. The people recovering from a medicalized bed, they go after to a hospital bed, and when they are fully recover, goes back to normal.

If the hospital gets overflowed, people stay at home without care (the illness goes faster and more chance to get worse and of passing away), and only goes to the hospital when happens to have a vacant bed (passed away of recovered). 

**-Autonomous:** We have the same hospital than conventional, and the process/protocol of illness is the same than in the conventional. However, people has at home "robotic sensitized houses" that takes care of you in the low level of infection, it takes care of you like in a "normal bed of the hospital" and sends you to the hospital as soon as you get worst (increasing your chance of surviving) 

In this case, I think that the hospital will not get overwhelmed in the normal beds, but yes in the medicalized... But if the "quarantine made district by district" is efficient, maybe the impact is lower... That is what we are interested din finding

**Comment by LAAP** [comment]
Awesome @agrignard, now I am running the model. Thanks!

I like a lot the red line following the infected people, and all the improvement that you are making to the simulation. I also have some questions:


<img width="1440" alt="Captura de pantalla 2020-04-27 a las 14 39 37" src="https://user-images.githubusercontent.com/19315213/80408884-e9120b80-8895-11ea-95c7-5353e4e47e49.png">

**-Time of response:**

1) Quarantine: It freeze the agents in the place where they are. Can we make them go home and stay at home depending on the % giving by the slider? It is Ok, if some "time of response" (latency) it is needed, before the measure have being steed. Also, people in quarantine goes shopping food, works in shops and hospitals, minimum services, etc. so we should keep that behavior of a small "X"% of people going from home to shops and Hospitals and some office, when quarantine

**-Control measures:**

2) Seems to me that in the simulation, quarantine, and masks drastically "stops" the pandemic, However, it is well-known that the people at home is still infecting people (family members and when they go shopping, etc.), and the masks, and social/physical distancing are not 100% efficient, so even if all 100% of the population are using this measures probably the pandemic will still "going on".

3) Social distancing: There is not control of social distancing, and not sure of what the "Social distancing visualization tag" doses.

**-Autonomy Vs Conventional:**

4) I think that it is confusing to have a tag that jumps from the scenario of Autonomy to Conventional without re-starting the simulation. Either we restart the simulation with that tag, or we rune both simulation at the same time and we visualize one or the other with the tag.

**Comment by agrignard** [comment]
Ok there start to have to many issues in the same issue here let me split it in more atomic ones as al of them are not straightforward conceptually and in term of code to solve:

https://github.com/CityScope/CS_Simulation_GAMA/issues/93
https://github.com/CityScope/CS_Simulation_GAMA/issues/94
https://github.com/CityScope/CS_Simulation_GAMA/issues/95
https://github.com/CityScope/CS_Simulation_GAMA/issues/96

Don't hesitate to create specific issues for specific question it wil ease the development and fixing o them
